#!/usr/bin/env bash
addToPathFront /home/skaluzhnyi/n/bin
addToPathFront $DENO_INSTALL
addToPath /home/skaluzhnyi/personal/lua-language-server/bin/Linux
addToPathFront /usr/local/go/bin
addToPath $GOPATH/bin
addToPath $HOME/work/wrapper
addToPath $HOME/.yarn/bin
addToPath /usr/lib/llvm-8/bin
addToPath $HOME/personal/uhh/build
addToPath $HOME/.cargo/bin
addToPath $HOME/.rustup

# ccache
addToPathFront /usr/lib/ccache
